### PR TITLE
Allow tuples of `Measure` in `polygon`. Fixes #190.

### LINKED ISSUE #190: introspect raises LoadError
I haven't been able to get `introspect` to work. 

Using the example from the docs in a JuliaBox:

```julia
tomato_bisque =
    compose(context(),
            (context(), circle(), fill("bisque")),
            (context(), rectangle(), fill("tomato")))
introspect(tomato_bisque)
```
```
LoadError: MethodError: `convert` has no method matching convert(::Type{Measures.Length{:cx,Float64}}, ::Measures.Add{Measures.Length{:cx,Float64},Measures.Length{:mm,Float64}})
This may have arisen from a call to the constructor Measures.Length{:cx,Float64}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  Measures.Length{U,T}(::Any)
  call{T}(::Type{T}, ::Any)
  convert{u,T1<:Number,T2<:Number}(::Type{Measures.Length{u,T1<:Number}}, !Matched::Measures.Length{u,T2<:Number})
  ...
while loading In[3], in expression starting on line 6

 in setindex! at array.jl:313
 in polygon at /home/juser/.julia/v0.4/Compose/src/form.jl:71
 in polygon at /home/juser/.julia/v0.4/Compose/src/form.jl:62
 in introspect at /home/juser/.julia/v0.4/Compose/src/container.jl:651
```

### PR DESCRIPTION
**Pull request by rohitvarkey**

### CODE REVIEW

**Comment by timholy** [comment]
I can't evaluate this. @shashi?

**Comment by shashi** [comment]
I can't figure out what the `narrow_polygon_point_types` is supposed to do.  It looks like

```
julia> Compose.narrow_polygon_point_types(Vector[[(1, 2)]])
(Any, Any)

julia> Compose.narrow_polygon_point_types(Vector[[(1mm, 2)]])
(Any,Any)

julia> Compose.narrow_polygon_point_types(Vector[[(1mm, 2mm)]])
(Measures.Length{:mm,Float64},Measures.Length{:mm,Float64})

julia> Compose.narrow_polygon_point_types(Vector[[(1mm, 2w)]])
(Measures.Length{:mm,Float64},Measures.Length{:w,Float64})

```

It doesn't look like a conversion mechanism to turn numbers into length values (or maybe it used to be and is no more) in the list comprehension

```
VecType[(x_measure(point[1]), y_measure(point[2]))
                     for point in points])]
```

@yeesian do you know?

**Comment by yeesian** [comment]
I haven't had occasion to dig into it before, but [based on the implementation](https://github.com/dcjones/Compose.jl/blob/master/src/misc.jl#L148-L194), it seems to be inferring the type of the points in the vector passed in.

**Comment by Hydrotoast** [comment]
@timholy @shashi @yeesian Is there any reason not to merge this?

**Pull request merged**
