### PR TITLE
Use Documenter.jl for documentation

### PR DESCRIPTION
**Pull request by Hydrotoast**
Start using `Documenter.jl` for documentation eventually push to `gh-pages` because the composejl.org domain name is down as seen in #210. This PR is the start of migrating the documentation.

Demo available here: https://hydrotoast.github.io/Compose.jl/latest/

**Issues**
- [x] Investigate why `nothing` is being printed at the top. See https://github.com/JuliaDocs/Documenter.jl/issues/191
- [x] Fix the logo (it doesn't look right and I can't seem to find a reference anywhere).
- [x] Example in issue #215 needs to be fixed.

compose_docs

@rsrock, perhaps you should review this since you mention that you have previous experience with `Documenter.jl` in `Images.jl`.

### CODE REVIEW

**Comment by rsrock** [comment]
Try this for the logo.  I extracted it just now from archive.org.

[composelogo.svg.zip](https://github.com/dcjones/Compose.jl/files/431207/composelogo.svg.zip)

**Comment by Hydrotoast** [comment]
Thanks, ill get around to this tonight unless someone wants to submit a PR
to my branch before then.

**Comment by tlnagy** [comment]
Can you set up a live demo for this? Like pushing to the `gh-pages` branch of your fork of `Compose`?

**Comment by Hydrotoast** [comment]
@tlnagy demo available here: https://hydrotoast.github.io/Compose.jl/latest/. This required an unreasonable amount of trial and error. Glad I've got it working now though. I had to use your `make.jl` as a reference in Gadfly.

**Comment by tlnagy** [comment]
A couple things

1. Thanks for doing this! 👍

2. Did you generate the `.documenter.enc` file? I think Daniel has to generate it to make autobuilding work properly.

3. Would it be possible to break it into a couple different pages?

**Comment by Hydrotoast** [comment]
Yes, I generated the .documenter.enc. Perhaps we can contact daniel to
generate another for this package?

In the meanwhile, I'll see what I can do about splitting this up into
multiple pages. The current structure is just the closest to the original
(single page).

**Comment by tlnagy** [comment]
Yeah, I can shoot him an email and see if he can do it. If we are updating the docs, we might as well redo the organization now.

**Comment by Hydrotoast** [comment]
@tlnagy Broke up the pages as requested. There isn't too much content on these docs. Perhaps a separate PR should address doc building.

**Comment by tlnagy** [comment]
Yeah, I changed my mind. Your original looked better, sorry. I pinged Daniel so hopefully he'll get back soon.

**Comment by Hydrotoast** [comment]
@tlnagy Reverted (via `git reset` so no extra commit)

**Comment by tlnagy** [comment]
Sorry about the noise, playing around with Github's new PR changes stuff. I think this is ready for merging once you add the author information back in. 🎉

**Comment by Hydrotoast** [comment]
@tlnagy Added the `@meta` block

**Comment by tlnagy** [comment]
awesome. lgtm. 🎉

**Comment by Hydrotoast** [comment]
@tlnagy Looks like Travis is having some issues pushing the documentation to the `gh-pages` branch:

```
Identity added: /home/travis/.julia/v0.5/Compose/docs/.documenter (/home/travis/.julia/v0.5/Compose/docs/.documenter)
Initialized empty Git repository in /tmp/tmplI0c2A/.git/
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: Cannot update paths and switch to branch 'gh-pages' at the same time.
Did you intend to checkout 'upstream/gh-pages' which can not be resolved as commit?
[master (root-commit) 815bd72] build based on 85efe7c
 16 files changed, 1734 insertions(+)
 create mode 100644 latest/assets/documenter.css
 create mode 100644 latest/assets/documenter.js
 create mode 100644 latest/assets/logo.svg
 create mode 100644 latest/assets/search.js
 create mode 100644 latest/assets/style.css
 create mode 100644 latest/circles.svg
 create mode 100644 latest/circles_fill_vectorized.svg
 create mode 100644 latest/cycled_circles.svg
 create mode 100644 latest/index.html
 create mode 100644 latest/search.html
 create mode 100644 latest/search_index.js
 create mode 100644 latest/sierpinski.svg
 create mode 100644 latest/tomato.svg
 create mode 100644 latest/tomato_bisque.svg
 create mode 100644 latest/tomato_bisque_triangle.svg
 create mode 100644 latest/tomatos.svg
Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I imagine the error could be:

- Deployment key in the repo settings does not have `write` permissions
- Deployment key in the repo settings is inconsistent with `.documenter.enc`

Since I haven't seen this error before, I imagine it's the `write` permissions.

**Comment by tlnagy** [comment]
No idea why this isn't working, any thoughts @MichaelHatherly?

**Comment by MichaelHatherly** [comment]
Yes, probably one of those two. Has the private key for `.documenter.enc` been added to the GitHub repo settings page?

**Comment by tlnagy** [comment]
Ah, that might be the problem. Let me ping Daniel again.

**Comment by Keno** [comment]
Maybe it's time to transfer Compose to an organization such that these administrativia don't require his attention?

**Pull request merged**
