### PR TITLE
introspect: add "R" for rectangle, "C" for circle, etc.

### PR DESCRIPTION
**Pull request by timholy**
I'm hoping this will be helpful as I dig into the architecture.

I can't distinguish `vcenter`, `vtop`, and `vbottom`, is this a bug?

### CODE REVIEW

**Comment by dcjones** [comment]
Thanks, this looks nice.

Vertical alignment works for me on `PNG` and `SVG`, but it could be at the whims of the browser for SVG or cairo's ability to compute text sizes for cairo backends.

If you're digging into the architecture, you should maybe take a look at the `measures` branch, which is work that @shashi and I did that simplifies and speeds things up quite a bit. I'm waiting to 0.4 to be released to merge it, because it assumes efficient tuples.

**Comment by shashi** [comment]
I wonder if https://github.com/JuliaLang/julia/issues/11187 thwarts our plans though

**Comment by dcjones** [comment]
You're worried that passing all tuples by reference will wipe out any performance improvement?

**Comment by shashi** [comment]
Yeah, could make it worse. But I haven't seen the numbers yet.

**Comment by dcjones** [comment]
@shashi I benchmarked an order-11 sierpinski triangle on `measures`.

On julia master:
2.526038 seconds (9.21 M allocations: 366.310 MB, 2.12% gc time)

One commit before https://github.com/JuliaLang/julia/commit/f2cce89ed2d4c535541dc31ad77b8b98f8e39d2d
2.273112 seconds (9.21 M allocations: 366.310 MB, 1.98% gc time)

So it is slower, but not dramatically. Compare this to `master`:

julia master:
8.549056 seconds (36.14 M allocations: 983.982 MB, 1.75% gc time)

https://github.com/JuliaLang/julia/commit/f2cce89ed2d4c535541dc31ad77b8b98f8e39d2d ~ 1
7.724505 seconds (36.14 M allocations: 983.982 MB, 1.24% gc time)

**Comment by shashi** [comment]
Nice! The change doesn't matter much at all. And whoa 9.21M allocations.

**Comment by dcjones** [comment]
Yeah, that seems a little crazy: `9.21e6 / 3^11` -> 52 allocations per triangle drawn! Clearly there's some more room for improvement.

**Pull request merged**
