### PR TITLE
minor fix to make Gadfly work

### PR DESCRIPTION
**Pull request by montyvesselinov**
Please merge. Gadfly fails to work without this change.

### CODE REVIEW

**Comment by ScottPJones** [comment]
How does Gadfly fail, in that case?  Is the failure only on v0.5 (master)? It generally isn't a good idea to use an abstract type in an immutable type - if the problem is when handling Unicode characters, does it work if you simply change `ASCIIString` to `UTF8String`?

**Comment by montyvesselinov** [comment]
submitted a new pull request to match the comment above

**Comment by ScottPJones** [comment]
In the future, it's not really necessary to close the pull request and open another one, you could simply make the change, squash the commits, and force push to your branch, and the PR will be updated.

**Comment by montyvesselinov** [comment]
will do.

**Pull request closed without merging**
