### PR TITLE
handle NaN/Inf properly when drawing cairo polygons

### PR DESCRIPTION
**Pull request by tbreloff**
Similar to my last PR.  Let me know if you see any issues.

### CODE REVIEW

**Comment by tbreloff** [comment]
Bump.  Did anyone have a chance to review this?

**Comment by ScottPJones** [comment]
@dcjones seems to be missing at the moment - however @aviks has been kind enough to recently merge 3 of my bug fixes recently.

**Comment by tbreloff** [comment]
Bump... who has merge permissions?  @aviks? @timholy?  Thanks

**Comment by tbreloff** [comment]
Thanks! :)

**Pull request merged**
